CREATE OR REPLACE VIEW bolton_portal.vw_pl_traceability_tuna AS
WITH expanded_pallets AS (
    SELECT
        src.pk,
        src.updated,
        src.username,
        src."packingListHeader.containerOrTruckNumber",
        src."packingListHeader.sequence",
        src."packingListHeader.version",
        src."packingListHeader.status",
        src."packingListSampling.time",
        src."packingListHeader.product.name",
        src."packingListHeader.oldestProductionDate",
        src."packingListHeader.supplier.name",
        src."packingListHeader.shippedTo",
        src."packingListHeader.address",
        src."packingListHeader.phone",
        src."packingListHeader.shippingDate",
        src."packingListHeader.seal",
        src."packingListHeader.cop",
        src."packingListHeader.temperatureChart",
        src."packingListHeader.euApprovalNumber",
        src."packingListHeader.eta",
        src."packingListHeader.otherInfo",
        src."packingListHeader.packingListInternalNumber",
        jsonb_array_elements(
            replace(
                replace(src."packingListSampling.lines.values", '''', '"'),
                'None',
                'null'
            )::jsonb
        ) AS p_data
    FROM bolton_portal.packing_list_quality_samples_bolton src
    WHERE src."packingListSampling.lines.values" LIKE '[%]'
),
expanded_fish_lots AS (
    SELECT
        ep.pk,
        ep.updated,
        ep.username,
        ep."packingListHeader.containerOrTruckNumber",
        ep."packingListHeader.sequence",
        ep."packingListHeader.version",
        ep."packingListHeader.status",
        ep."packingListSampling.time",
        ep."packingListHeader.product.name",
        ep."packingListHeader.oldestProductionDate",
        ep."packingListHeader.supplier.name",
        ep."packingListHeader.shippedTo",
        ep."packingListHeader.address",
        ep."packingListHeader.phone",
        ep."packingListHeader.shippingDate",
        ep."packingListHeader.seal",
        ep."packingListHeader.cop",
        ep."packingListHeader.temperatureChart",
        ep."packingListHeader.euApprovalNumber",
        ep."packingListHeader.eta",
        ep."packingListHeader.otherInfo",
        ep."packingListHeader.packingListInternalNumber",
        ep.p_data,
        jsonb_array_elements((ep.p_data -> 'fishLotdata') -> 'values') AS f_data
    FROM expanded_pallets ep
),
flattened AS (
    SELECT
        efl."packingListHeader.containerOrTruckNumber" AS container,
        efl.p_data ->> 'palletId' AS pallet,
        efl.pk AS id,
        efl."packingListHeader.sequence" AS number,
        efl."packingListHeader.version" AS version,
        efl."packingListHeader.status" AS status,
        efl."packingListSampling.time" AS form_date,
        efl.updated AS last_update,
        efl.username AS last_update_user,
        NULL::text AS visible_ba,
        efl."packingListHeader.product.name" AS product_ref,
        NULL::text AS product_ref_descr,
        efl."packingListHeader.oldestProductionDate" AS oldest_prod_date,
        efl.p_data ->> 'sapCode' AS sapcode,
        NULL::text AS name,
        efl."packingListHeader.supplier.name" AS broker_name,
        efl."packingListHeader.shippedTo" AS shipped_to,
        efl."packingListHeader.address" AS address,
        efl."packingListHeader.phone" AS phone,
        efl."packingListHeader.phone" AS vessel_header,
        efl."packingListHeader.shippingDate" AS shipping_date,
        efl."packingListHeader.seal" AS seal,
        NULL::text AS invoice,
        efl."packingListHeader.cop" AS cop,
        efl."packingListHeader.temperatureChart" AS temperature_chart,
        efl."packingListHeader.euApprovalNumber" AS eu_approval_number,
        efl."packingListHeader.eta" AS eta,
        efl."packingListHeader.otherInfo" AS other_info,
        efl."packingListHeader.packingListInternalNumber" AS pl_internal_number,
        NULL::text AS is_custom_lot,
        NULL::text AS custom_lot_year,
        NULL::text AS pl_id,
        NULL::text AS pallet_tare,
        efl.p_data ->> 'netWeight' AS loin_weight,
        efl.p_data ->> 'palletNetWeight' AS plt_net_weight,
        efl.p_data ->> 'palletGrossWeight' AS plt_gross_weight,
        efl.p_data ->> 'batch' AS batch,
        efl.p_data ->> 'commonDate' AS common_date,
        efl.p_data ->> 'size' AS size,
        efl.p_data ->> 'commonLot' AS common_fish_lot,
        efl.p_data ->> 'tripFrom' AS trip_from,
        efl.p_data ->> 'tripTo' AS trip_to,
        efl.p_data ->> 'vessel' AS vessel,
        NULL::text AS vessel_flag,
        NULL::text AS imo,
        efl.p_data ->> 'gear' AS fishing_gear,
        NULL::text AS ocean_capture,
        (efl.f_data -> 'ocean') ->> 'fao' AS fao_fishing_area,
        efl.f_data ->> 'additional' AS additional_information,
        efl.f_data ->> 'vesselGrossTonn' AS gross_tonn,
        efl.f_data ->> 'landingType' AS direct_landing,
        efl.f_data ->> 'landingType' AS carrier_container,
        (efl.f_data -> 'transhipmentVessel') ->> 'name' AS transhipment_vessel,
        (efl.f_data -> 'transhipmentVessel') ->> 'vesselFlagState' AS transhipment_vessel_flag,
        NULL::text AS carrier_number,
        NULL::text AS other,
        (efl.f_data -> 'unloadingPort') ->> 'name' AS port_of_landing,
        ((efl.f_data -> 'unloadingPort') -> 'country') ->> 'name' AS port_of_landing_flag,
        NULL::text AS ba_approved_in_creation,
        efl.p_data ->> 'salt' AS salt_avg,
        efl.p_data ->> 'histamine' AS istamine_max,
        NULL::text AS istamine_max_lq,
        efl.p_data ->> 'moisture' AS moisture_avg,
        NULL::text AS national_register,
        NULL::text AS fats_avg,
        NULL::text AS weight_avg,
        NULL::text AS latin_species,
        NULL::text AS expiry_date,
        efl.p_data ->> 'sapCode' AS sap_code,
        NULL::text AS purpose,
        efl.p_data ->> 'sampling' AS sampling,
        efl.p_data ->> 'numberOfsamples' AS num_histamine_samples,
        NULL::text AS description
    FROM expanded_fish_lots efl
)
SELECT
    NULL::text AS "PRODUCER_NAME",
    NULL::text AS "PRODUCER_SAPCODE",
    NULL::text AS "PRODUCER_VATCODE",
    NULL::text AS "PRODUCER_COUNTRY",
    NULL::text AS "PRODUCER_CITY",
    NULL::text AS "PRODUCER_STREET",
    NULL::text AS "PRODUCER_STREETNUMBER",
    NULL::text AS "PRODUCER_CAP",
    NULL::text AS "PRODUCER_PHONE",
    NULL::text AS "PRODUCER_MAIL",
    flattened.broker_name AS "BROKER_NAME",
    NULL::text AS "BROKER_SAPCODE",
    NULL::text AS "BROKER_VATCODE",
    NULL::text AS "BROKER_COUNTRY",
    NULL::text AS "BROKER_CITY",
    NULL::text AS "BROKER_STREET",
    NULL::text AS "BROKER_STREETNUMBER",
    NULL::text AS "BROKER_CAP",
    NULL::text AS "BROKER_PHONE",
    NULL::text AS "BROKER_MAIL",
    NULL::text AS "HEADER_STATE_DESCR",
    flattened.id AS "HEADER_ID",
    flattened.number AS "HEADER_NUMBER",
    flattened.version AS "HEADER_VERSION",
    flattened.status AS "HEADER_STATE",
    NULL::text AS "HEADER_PENDING",
    flattened.visible_ba AS "HEADER_VISIBLE_BA",
    NULL::text AS "HEADER_PRODUCER_ID",
    flattened.form_date AS "HEADER_FORM_DATE",
    flattened.eu_approval_number AS "HEADER_EU_APPROVAL_NUMBER",
    flattened.other_info AS "HEADER_OTHER_INFO",
    NULL::text AS "HEADER_SOLD_TO_ID",
    NULL::text AS "HEADER_SOLD_TO",
    NULL::text AS "HEADER_DESTINATION_ID",
    NULL::text AS "HEADER_DESTINATION_NAME",
    flattened.shipped_to AS "HEADER_SHIPPED_TO",
    flattened.address AS "HEADER_ADDRESS",
    flattened.phone AS "HEADER_PHONE",
    flattened.vessel_header AS "HEADER_SHIPPINGVESSEL_VOYAGE_N",
    flattened.shipping_date AS "HEADER_SHIPPING_DATE",
    NULL::text AS "HEADER_PORT_OF_DESTINATION",
    NULL::text AS "HEADER_PORT_OF_LOADING",
    flattened.container AS "HEADER_CONTAINER",
    NULL::text AS "HEADER_IS_CONTAINER",
    NULL::text AS "HEADER_TRUCK",
    flattened.seal AS "HEADER_SEAL",
    flattened.invoice AS "HEADER_INVOICE",
    NULL::text AS "HEADER_ORDER_NUMBER",
    flattened.cop AS "HEADER_COP",
    flattened.eta AS "HEADER_ETA",
    flattened.temperature_chart AS "HEADER_TEMPERATURE_CHART",
    flattened.product_ref AS "HEADER_PRODUCT_REF",
    flattened.product_ref_descr AS "HEADER_PRODUCT_REF_DESCR",
    NULL::text AS "HEADER_PRODUCT_REF_CODE",
    flattened.oldest_prod_date AS "HEADER_OLDEST_PROD_DATE",
    flattened.pl_internal_number AS "HEADER_PL_INTERNAL_NUMBER",
    NULL::text AS "HEADER_GROSS_WEIGHT",
    NULL::text AS "HEADER_LOIN_WEIGHT",
    NULL::text AS "HEADER_BOX_WEIGHT",
    flattened.name AS "HEADER_BROKER",
    flattened.broker_name AS "HEADER_BROKER_NAME",
    NULL::text AS "HEADER_TOT_BAGS_NUM",
    NULL::text AS "HEADER_TOT_NET_WEIGHT",
    NULL::text AS "HEADER_TOT_PALLET_GROSS_WEIGHT",
    NULL::text AS "HEADER_TOT_PALLET_NET_WEIGHT",
    NULL::text AS "HEADER_IS_LAST_VERSION",
    flattened.is_custom_lot AS "HEADER_IS_CUSTOM_LOT",
    flattened.custom_lot_year AS "HEADER_CUSTOM_LOT_YEAR",
    NULL::text AS "HEADER_ID_MPA",
    flattened.pl_id AS "ROW_PL_ID",
    NULL::text AS "ROW_ROW_NUM",
    flattened.pallet AS "ROW_PALLET",
    flattened.pallet_tare AS "ROW_PALLET_TARE",
    flattened.loin_weight AS "ROW_LOIN_WEIGHT",
    NULL::text AS "ROW_PROGRESSIVE_NUMBER",
    NULL::text AS "ROW_PRODUCTION_DATE",
    NULL::text AS "ROW_PRODUCTION_LOT",
    flattened.common_fish_lot AS "ROW_FISH_LOT",
    flattened.size AS "ROW_SIZE",
    NULL::text AS "ROW_BAGS_NUM",
    NULL::text AS "ROW_NET_WEIGHT",
    flattened.plt_net_weight AS "ROW_PLT_NET_WEIGHT",
    flattened.plt_gross_weight AS "ROW_PLT_GROSS_WEIGHT",
    flattened.trip_from AS "ROW_TRIP_FROM",
    flattened.trip_to AS "ROW_TRIP_TO",
    flattened.vessel AS "ROW_VESSEL",
    flattened.vessel_flag AS "ROW_VESSEL_FLAG",
    NULL::text AS "ROW_VESSEL_FLAG_DESCR",
    flattened.fishing_gear AS "ROW_FISHING_GEAR",
    NULL::text AS "ROW_FISHING_GEAR_DESCR",
    flattened.ocean_capture AS "ROW_OCEAN_CAPTURE",
    NULL::text AS "ROW_OCEAN_CAPTURE_DESCR",
    flattened.fao_fishing_area AS "ROW_FAO_FISHING_AREA",
    flattened.imo AS "ROW_IMO",
    flattened.national_register AS "ROW_NATIONAL_REGISTER",
    flattened.salt_avg AS "ROW_SALT_AVG",
    flattened.istamine_max AS "ROW_HISTAMINE_MAX",
    flattened.istamine_max_lq AS "ROW_HISTAMINE_MAX_LQ",
    flattened.moisture_avg AS "ROW_MOISTURE_AVG",
    flattened.fats_avg AS "ROW_FATS_AVG",
    flattened.expiry_date AS "ROW_EXPIRY_DATE",
    NULL::text AS "ROW_NUMBER_OF_BOXES",
    flattened.transhipment_vessel AS "ROW_TRANSHIPMENT_VESSEL",
    flattened.transhipment_vessel_flag AS "ROW_TRANSHIPMENT_VESSEL_FLAG",
    NULL::text AS "ROW_TRANS_VESS_FLAG_DESCR",
    flattened.carrier_number AS "ROW_CARRIER_NUMBER",
    flattened.carrier_container AS "ROW_CARRIER_CONTAINER",
    flattened.other AS "ROW_OTHER",
    flattened.additional_information AS "ROW_ADDITIONAL_INFORMATION",
    flattened.port_of_landing AS "ROW_PORT_OF_LANDING",
    flattened.port_of_landing_flag AS "ROW_PORT_OF_LANDING_FLAG",
    NULL::text AS "ROW_PORT_OF_LANDING_FLAG_DESCR",
    CASE
        WHEN flattened.ba_approved_in_creation = '0' THEN 'Not approved'
        WHEN flattened.ba_approved_in_creation = '1' THEN 'Approved'
        ELSE 'N/A'
    END AS "ROW_BA_APPROVED_IN_CREATION",
    flattened.batch AS "ROW_BATCH",
    flattened.common_date AS "ROW_COMMON_DATE",
    flattened.sap_code AS "ROW_SAP_CODE",
    NULL::text AS "ROW_SSCC_CODE",
    NULL::text AS "ROW_WARE_ENTRY_DATE",
    NULL::text AS "ROW_WARE_LOCATION",
    NULL::text AS "ROW_ENTRY_DATE",
    flattened.common_fish_lot AS "ROW_COMMON_FISH_LOT",
    flattened.purpose AS "ROW_PURPOSE",
    flattened.sampling AS "ROW_SAMPLING",
    flattened.num_histamine_samples AS "ROW_NUM_HISTAMINE_SAMPLES",
    flattened.latin_species AS "ROW_LATIN_SPECIES",
    flattened.product_ref_descr AS "PRODUCT_REFERENCE_DESCRIPTION",
    NULL::text AS "PRODUCT_REFERENCE_MPA_ID",
    flattened.description AS "DESCRIPTION",
    NULL::integer AS "PRODUCT_SAPCODE_CERTIFIED_MSC",
    NULL::text AS "VESSEL_CERTIFICATION_STATUS",
    NULL::text AS "VESSEL_CERTIFICATION_FISHERY"
FROM flattened
WHERE
    flattened.status IN ('CONFIRMED', 'PARTIALLY RECEIVED', 'RECEIVED')
    AND (
        flattened.batch LIKE 'A%'
        OR flattened.batch LIKE 'B%'
        OR flattened.batch IS NULL
    );
